// Code generated by values-gen. DO NOT EDIT.
// +kubebuilder:object:generate=true
// +groupName=apps.cozystack.io
// +versionName=v1alpha1
package postgresql

import (
	resource "k8s.io/apimachinery/pkg/api/resource"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
)

// +kubebuilder:object:root=true
type Config struct {
	v1.TypeMeta   `json:",inline"`
	v1.ObjectMeta `json:"metadata,omitempty"`
	Spec          ConfigSpec `json:"spec,omitempty"`
}

type ConfigSpec struct {
	// Number of Postgres replicas.
	// +kubebuilder:default:=2
	Replicas int `json:"replicas"`
	// Explicit CPU and memory configuration for each PostgreSQL replica. When omitted, the preset defined in `resourcesPreset` is applied.
	// +kubebuilder:default:={}
	Resources Resources `json:"resources,omitempty"`
	// Default sizing preset used when `resources` is omitted.
	// +kubebuilder:default:="micro"
	ResourcesPreset ResourcesPreset `json:"resourcesPreset"`
	// Persistent Volume Claim size available for application data.
	// +kubebuilder:default:="10Gi"
	Size resource.Quantity `json:"size"`
	// StorageClass used to store the data.
	// +kubebuilder:default:=""
	StorageClass string `json:"storageClass"`
	// Enable external access from outside the cluster.
	// +kubebuilder:default:=false
	External bool `json:"external"`
	// PostgreSQL major version to deploy
	// +kubebuilder:default:="v18"
	Version Version `json:"version"`
	// PostgreSQL server configuration.
	// +kubebuilder:default:={}
	Postgresql PostgreSQL `json:"postgresql"`
	// Quorum configuration for synchronous replication.
	// +kubebuilder:default:={}
	Quorum Quorum `json:"quorum"`
	// Users configuration map.
	// +kubebuilder:default:={}
	Users map[string]User `json:"users,omitempty"`
	// Databases configuration map.
	// +kubebuilder:default:={}
	Databases map[string]Database `json:"databases,omitempty"`
	// Backup configuration.
	// +kubebuilder:default:={}
	Backup Backup `json:"backup"`
	// Bootstrap configuration.
	// +kubebuilder:default:={}
	Bootstrap Bootstrap `json:"bootstrap"`
}

type Backup struct {
	// Destination path for backups (e.g. s3://bucket/path/).
	// +kubebuilder:default:="s3://bucket/path/to/folder/"
	DestinationPath string `json:"destinationPath,omitempty"`
	// Enable regular backups.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// S3 endpoint URL for uploads.
	// +kubebuilder:default:="http://minio-gateway-service:9000"
	EndpointURL string `json:"endpointURL,omitempty"`
	// Retention policy (e.g. "30d").
	// +kubebuilder:default:="30d"
	RetentionPolicy string `json:"retentionPolicy,omitempty"`
	// Access key for S3 authentication.
	// +kubebuilder:default:="<your-access-key>"
	S3AccessKey string `json:"s3AccessKey,omitempty"`
	// Secret key for S3 authentication.
	// +kubebuilder:default:="<your-secret-key>"
	S3SecretKey string `json:"s3SecretKey,omitempty"`
	// Cron schedule for automated backups.
	// +kubebuilder:default:="0 2 * * * *"
	Schedule string `json:"schedule,omitempty"`
}

type Bootstrap struct {
	// Whether to restore from a backup.
	// +kubebuilder:default:=false
	Enabled bool `json:"enabled"`
	// Previous cluster name before deletion (matches serverName in backup.info).
	// +kubebuilder:default:=""
	OldName string `json:"oldName"`
	// Timestamp (RFC3339) for point-in-time recovery; empty means latest.
	// +kubebuilder:default:=""
	RecoveryTime string `json:"recoveryTime,omitempty"`
	// Barman server name from the old cluster's backup.info. Use when the original cluster used a different serverName than its Kubernetes cluster name.
	// +kubebuilder:default:=""
	ServerName string `json:"serverName,omitempty"`
}

type Database struct {
	// List of enabled PostgreSQL extensions.
	Extensions []string `json:"extensions,omitempty"`
	// Roles assigned to users.
	Roles DatabaseRoles `json:"roles,omitempty"`
}

type DatabaseRoles struct {
	// List of users with admin privileges.
	Admin []string `json:"admin,omitempty"`
	// List of users with read-only privileges.
	Readonly []string `json:"readonly,omitempty"`
}

type PostgreSQL struct {
	// PostgreSQL server parameters.
	// +kubebuilder:default:={}
	Parameters PostgreSQLParameters `json:"parameters,omitempty"`
}

type PostgreSQLParameters struct {
	// Maximum number of concurrent connections to the database server.
	// +kubebuilder:default:=100
	MaxConnections int `json:"max_connections,omitempty"`
}

type Quorum struct {
	// Maximum number of synchronous replicas allowed (must be less than total replicas).
	// +kubebuilder:default:=0
	MaxSyncReplicas int `json:"maxSyncReplicas"`
	// Minimum number of synchronous replicas required for commit.
	// +kubebuilder:default:=0
	MinSyncReplicas int `json:"minSyncReplicas"`
}

type Resources struct {
	// CPU available to each replica.
	Cpu resource.Quantity `json:"cpu,omitempty"`
	// Memory (RAM) available to each replica.
	Memory resource.Quantity `json:"memory,omitempty"`
}

type User struct {
	// Password for the user.
	Password string `json:"password,omitempty"`
	// Whether the user has replication privileges.
	Replication bool `json:"replication,omitempty"`
}

// +kubebuilder:validation:Enum="nano";"micro";"small";"medium";"large";"xlarge";"2xlarge"
type ResourcesPreset string

// +kubebuilder:validation:Enum="v18";"v17";"v16";"v15";"v14";"v13"
type Version string
