apiVersion: v1
kind: ConfigMap
metadata:
  name: cozystack-scheduler-config
  namespace: {{ .Release.Namespace }}
data:
  scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: true
      resourceNamespace: {{ .Release.Namespace }}
      resourceName: cozystack-scheduler
    profiles:
      - schedulerName: cozystack-scheduler
        plugins:
          preFilter:
            disabled:
              - name: InterPodAffinity
              - name: NodeAffinity
              - name: PodTopologySpread
            enabled:
              - name: CozystackInterPodAffinity
              - name: CozystackNodeAffinity
              - name: CozystackPodTopologySpread
              - name: CozystackSchedulingClass
          filter:
            disabled:
              - name: InterPodAffinity
              - name: NodeAffinity
              - name: PodTopologySpread
            enabled:
              - name: CozystackInterPodAffinity
              - name: CozystackNodeAffinity
              - name: CozystackPodTopologySpread
              - name: CozystackSchedulingClass
          preScore:
            disabled:
              - name: InterPodAffinity
              - name: NodeAffinity
              - name: PodTopologySpread
            enabled:
              - name: CozystackInterPodAffinity
              - name: CozystackNodeAffinity
              - name: CozystackPodTopologySpread
          score:
            disabled:
              - name: InterPodAffinity
              - name: NodeAffinity
              - name: PodTopologySpread
            enabled:
              - name: CozystackInterPodAffinity
              - name: CozystackNodeAffinity
              - name: CozystackPodTopologySpread
    {{- with .Values.extenders }}
    extenders:
      {{- toYaml . | nindent 6 }}
    {{- end }}
