---
apiVersion: cozystack.io/v1alpha1
kind: PackageSource
metadata:
  name: cozystack.cozystack-scheduler
spec:
  sourceRef:
    kind: OCIRepository
    name: cozystack-packages
    namespace: cozy-system
    path: /
  variants:
  - name: default
    components:
    - name: cozystack-scheduler
      path: system/cozystack-scheduler
      install:
        namespace: kube-system
        releaseName: cozystack-scheduler
  - name: linstor
    dependsOn:
    - cozystack.linstor-scheduler
    components:
    - name: cozystack-scheduler
      path: system/cozystack-scheduler
      valuesFiles:
      - values-linstor.yaml
      install:
        namespace: kube-system
        releaseName: cozystack-scheduler
